In [9]:
import pandas as pd
df_train = pd.read_csv('fraudTrain.csv')
df_test = pd.read_csv('fraudTest.csv')

In [10]:
df_train.drop('Unnamed: 0', axis=1, inplace= True)
df_test.drop('Unnamed: 0', axis=1, inplace= True)

In [3]:
df_train.head(5)

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [7]:
df_train.isnull().sum()

trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [8]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 22 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   trans_date_trans_time  1296675 non-null  object
 1   cc_num                 1296675 non-null  int64
 2   merchant               1296675 non-null  object
 3   category               1296675 non-null  object
 4   amt                    1296675 non-null  float64
 5   first                  1296675 non-null  object
 6   last                   1296675 non-null  object
 7   gender                 1296675 non-null  object
 8   street                 1296675 non-null  object
 9   city                   1296675 non-null  object
 10  state                  1296675 non-null  object
 11  zip                    1296675 non-null  int64
 12  lat                    1296675 non-null  float64
 13  long                   1296675 non-null  float64
 14  city_pop               1296675 non-null  int64
 15  job                    1296675 non-null  object
 16  dob                    1296675 non-null  object
 17  trans_num              1296675 non-null  object
 18  unix_time              1296675 non-null  int64
 19  merch_lat              1296675 non-null  float64
 20  merch_long             1296675 non-null  float64
 21  is_fraud               1296675 non-null  int64
dtypes: float64(5), int64(5), object(12)
memory usage: 217.6+ MB

In [9]:
df_train.duplicated().sum()

0

In [146]:
X_train.head(5)

,cc_num,merchant,category,amt,first,last,gender,street,city,state,...,trans_num,unix_time,merch_lat,merch_long,trans_year,trans_month,trans_day,trans_hour,trans_minute,trans_second
738073,30546453310167,fraud_Hermann and Sons,shopping_pos,1.25,Nicholas,Tran,M,672 Randall Burg Suite 551,Belmont,NH,...,223d637a6feb692dfe1e6870f8e11600,1352632471,42.516757,-70.620835,2019,11,11,11,14,31
652781,180042946491150,fraud_Cartwright PLC,kids_pets,17.77,Charles,Robles,M,3337 Lisa Divide,Saint Petersburg,FL,...,9fc6e13735fe22227ed8888c5fc42100,1349442575,26.846154,-83.252528,2019,10,5,13,9,35
1219497,3550554389581384,fraud_Murray-Smitham,grocery_pos,95.53,Ryan,Foster,M,03921 Cole Mission Suite 882,Hampton,FL,...,c9756232a10184712cfc3c0a7ca3d9e6,1369450078,28.915593,-82.929278,2020,5,25,2,47,58
1215834,4562827002127,fraud_Smitham-Schiller,grocery_net,42.02,Christopher,Johnson,M,28711 Kristine Junction Suite 309,Greenville,OH,...,9ec039f99930dc109393b409971dd59f,1369357437,40.466064,-85.327887,2020,5,24,1,3,57
633170,4025612008285111,fraud_Schmidt-Larkin,home,82.11,Krystal,Key,F,23142 Montoya Island Apt. 742,Corsica,PA,...,d2a9e6eb99627e3139693aed48feb59f,1348680187,41.437287,-80.081485,2019,9,26,17,23,7

In [147]:
X_test.head(5)

,cc_num,merchant,category,amt,first,last,gender,street,city,state,...,trans_num,unix_time,merch_lat,merch_long,trans_year,trans_month,trans_day,trans_hour,trans_minute,trans_second
375815,4587657402165341815,"fraud_Moore, Dibbert and Koepp",misc_net,21.11,Amber,Lewis,F,6296 John Keys Suite 858,Pembroke Township,IL,...,96c918d59752695de799dadf94931984,1340395177,40.744108,-86.976153,2019,6,22,19,59,37
447408,2291163933867244,fraud_Harber Inc,gas_transport,87.34,Jeff,Elliott,M,351 Darlene Green,Columbia,SC,...,b82d03bd33fa5e29b65707edf66c5c58,1342587255,33.617314,-80.797801,2019,7,18,4,54,15
263037,371284100299909,fraud_Lockman Ltd,grocery_pos,126.76,Hannah,Thomas,F,1004 Willis Pass,Hedley,TX,...,948fdd42ba2c850acf7cd1d30fcb438d,1336716900,35.673058,-101.365566,2019,5,11,6,15,0
478405,4836998673805450,"fraud_Effertz, Welch and Schowalter",entertainment,26.78,Susan,Hardy,F,516 Brown Parks,Manistique,MI,...,1bd9c30c7f2a467ee31048fdc4e9c689,1343513398,46.521841,-86.049788,2019,7,28,22,9,58
1231,6595970453799027,"fraud_Hagenes, Kohler and Hoppe",food_dining,31.19,Gina,Gomez,F,72030 Shelton Crossing Apt. 742,Stirling,NJ,...,435abb30825fb92190805a3e31a19462,1325428451,41.398262,-73.768721,2019,1,1,14,34,11

In [15]:
X_train = df_train.drop('is_fraud', axis=1)
y_train = df_train['is_fraud']

X_test = df_test.drop('is_fraud', axis=1)
y_test = df_test['is_fraud']

In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder

# Convert datetime column to separate features
def process_datetime(df):
    df['trans_date_trans_time'] = pd.to_datetime(df['trans_date_trans_time'])
    df['trans_year'] = df['trans_date_trans_time'].dt.year
    df['trans_month'] = df['trans_date_trans_time'].dt.month
    df['trans_day'] = df['trans_date_trans_time'].dt.day
    df['trans_hour'] = df['trans_date_trans_time'].dt.hour
    df['trans_minute'] = df['trans_date_trans_time'].dt.minute
    df['trans_second'] = df['trans_date_trans_time'].dt.second
    df.drop('trans_date_trans_time', axis=1, inplace=True)
    return df

X_train_processed = process_datetime(X_train)
X_test_processed = process_datetime(X_test)

categorical_columns = ['merchant', 'category', 'first', 'last', 'gender', 'street', 'city', 'state', 'job']
numerical_columns = ['cc_num', 'amt', 'zip', 'lat', 'long', 'city_pop', 'unix_time', 'merch_lat',
                     'merch_long', 'trans_year', 'trans_month', 'trans_day', 'trans_hour', 'trans_minute', 'trans_second']

column_transformer = ColumnTransformer(
transformers= [
    ('encoder', OneHotEncoder(sparse_output=True, handle_unknown='ignore'), categorical_columns),
    ('scaler', StandardScaler(), numerical_columns)
],
    remainder='drop')

X_train_transformed = column_transformer.fit_transform(X_train_processed)
X_test_transformed = column_transformer.transform(X_test_processed)

##### Decision Tree Classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree, metrics
from sklearn.tree import plot_tree

clf = DecisionTreeClassifier()
clf.fit(X_train_tranformed, y_train)

In [37]:
clf.score(X_test_transformed, y_test)

0.9972126200471821

##### Logistic Regression

In [17]:
from sklearn.linear_model import LogisticRegression 
modelLR = LogisticRegression(max_iter=1000)
modelLR.fit(X_train_transformed, y_train)

LogisticRegression(max_iter=1000)

In [50]:
modelLR.score(X_test_transformed, y_test)

0.9958234287472626